
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  adapter: postgresql
  database: forestsat_demo
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: forestsat_demo_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: ENV['DB_NAME']
  pool: 5
  timeout: 5000
